services:
  bWAPP:
    image: "hackersploit/bwapp-docker"
    user: root
    ports:
      - "80:80"
#    privileged: true
    cap_add:
      - ALL
    security_opt:
      - seccomp=./seccomp-profiles/bwapp-seccomp.json
  FALCO:
    image: "falcosecurity/falco:0.42.0"
    privileged: true
    command: ["falco", "-U"]
    volumes:
      - /sys/kernel/tracing:/sys/kernel/tracing:ro
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /proc:/host/proc:ro
      - /etc:/host/etc:ro
      - ./falco-rules/falco_rules.local.yaml:/etc/falco/falco_rules.local.yaml:ro
    logging:
      driver: "json-file"